name: glimo
description: "Glimo - Personal Development Version"
publish_to: 'none'
version: 1.0.3+42

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^3.0.0
  flutter_riverpod: ^3.0.0
  go_router: ^17.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.14.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  wave: ^0.2.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  google_sign_in: ^6.2.1
  freezed_annotation: ^3.1.0
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  flutter_background_service: ^5.0.12
  flutter_background_service_android: ^6.2.5
  flutter_local_notifications: ^19.5.0
  fl_chart: ^0.69.0
  activity_recognition_flutter: ^5.0.0
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.3.6
  in_app_purchase_storekit: ^0.3.16
  k_means_cluster: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.13
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/LOGO GLEMO GAMBAR SAJA.png"
  min_sdk_android: 21
  remove_alpha_ios: true