// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf5FJI-0V_yfLd6BWziTksgWrZC6E6JoQ',
    appId: '1:279294323481:web:c311f3fd94d66c3b303388',
    messagingSenderId: '279294323481',
    projectId: 'glimo-2eff0',
    authDomain: 'glimo-2eff0.firebaseapp.com',
    storageBucket: 'glimo-2eff0.firebasestorage.app',
    measurementId: 'G-1J62YL73GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn08LFcsBjUUfMkcvlj4ha8RnNe9jhMyM',
    appId: '1:279294323481:android:81eff7de7699e087303388',
    messagingSenderId: '279294323481',
    projectId: 'glimo-2eff0',
    storageBucket: 'glimo-2eff0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdCx0b9cwP7wrh0YGZ7A0a7HWoa7JOaZ8',
    appId: '1:279294323481:ios:30fc2e426630763f303388',
    messagingSenderId: '279294323481',
    projectId: 'glimo-2eff0',
    storageBucket: 'glimo-2eff0.firebasestorage.app',
    iosBundleId: 'com.glemates.glimo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdCx0b9cwP7wrh0YGZ7A0a7HWoa7JOaZ8',
    appId: '1:279294323481:ios:4e93a3e52a4dd135303388',
    messagingSenderId: '279294323481',
    projectId: 'glimo-2eff0',
    storageBucket: 'glimo-2eff0.firebasestorage.app',
    iosBundleId: 'com.glemates.glimo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf5FJI-0V_yfLd6BWziTksgWrZC6E6JoQ',
    appId: '1:279294323481:web:78ad5e40a2381add303388',
    messagingSenderId: '279294323481',
    projectId: 'glimo-2eff0',
    authDomain: 'glimo-2eff0.firebaseapp.com',
    storageBucket: 'glimo-2eff0.firebasestorage.app',
    measurementId: 'G-733YY646YG',
  );
}
